class SHT31Reading:
    TemperatureC: float
    TemperatureF: float
    Humidity: float
    ERR: int

    def __init__(
        self,
        temperature_c: float = ...,
        humidity: float = ...,
        err: int = ...,
    ) -> None: ...


class SHT31:
    DEFAULT_ADDRESS: int

    REPEATABILITY_HIGH: str
    REPEATABILITY_MEDIUM: str
    REPEATABILITY_LOW: str

    eRepeatability_High: str
    eRepeatability_Medium: str
    eRepeatability_Low: str

    MEASURE_FREQ_0_5HZ: float
    MEASURE_FREQ_1HZ: int
    MEASURE_FREQ_2HZ: int
    MEASURE_FREQ_4HZ: int
    MEASURE_FREQ_10HZ: int

    eMeasureFreq_Hz5: float
    eMeasureFreq_1Hz: int
    eMeasureFreq_2Hz: int
    eMeasureFreq_4Hz: int
    eMeasureFreq_10Hz: int

    def __init__(
        self,
        i2c = ...,
        scl_pin: int | None = ...,
        sda_pin: int | None = ...,
        bus: int = ...,
        freq: int = ...,
        address: int = ...,
    ) -> None: ...

    def begin(self) -> int: ...
    def read_status(self) -> int: ...
    def read_serial_number(self) -> int: ...
    def soft_reset(self) -> bool: ...
    def heater_enable(self) -> bool: ...
    def heater_disable(self) -> bool: ...
    def clear_status_register(self) -> None: ...
    def read_alert_state(self) -> bool: ...
    def start_periodic_mode(self, measure_frequency: float | int, repeatability: str = ...) -> bool: ...
    def stop_periodic_mode(self) -> bool: ...
    def read_temperature_and_humidity(self, repeatability: str | None = ...) -> SHT31Reading: ...
    def get_temperature_c(self) -> float: ...
    def get_temperature_f(self) -> float: ...
    def get_humidity_rh(self) -> float: ...
    def read(self) -> tuple[float, float]: ...
    def temp(self) -> float: ...
    def humidity(self) -> float: ...

    def readSerialNumber(self) -> int: ...
    def softReset(self) -> bool: ...
    def heaterEnable(self) -> bool: ...
    def heaterDisable(self) -> bool: ...
    def clearStatusRegister(self) -> None: ...
    def readAlertState(self) -> bool: ...
    def startPeriodicMode(self, measure_frequency: float | int, repeatability: str = ...) -> bool: ...
    def stopPeriodicMode(self) -> bool: ...
    def readTemperatureAndHumidity(self, repeatability: str | None = ...) -> SHT31Reading: ...
    def getTemperatureC(self) -> float: ...
    def getTemperatureF(self) -> float: ...
    def getHumidityRH(self) -> float: ...


SEN0385 = SHT31
